name: Deploy Nuxt site to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: nuxt
      
      - name: Install dependencies
        run: npm ci
      
      - name: Update nuxt.config.ts
        run: |
          cat > nuxt.config.ts << EOF
          export default defineNuxtConfig({
            ssr: false,
            app: {
              baseURL: '/clean-day/'
            },
            nitro: {
              preset: 'github-pages',
              prerender: {
                failOnError: false,
                routes: ['/']
              }
            },
            devtools: { enabled: true },
            typescript: {
              strict: true
            },
            experimental: {
              renderJsonPayloads: true
            }
          })
          EOF
      
      # Add this step to help debugging
      - name: Create fallback .nojekyll file
        run: touch .nojekyll
      
      # Modify the build command to skip SSR/prerendering entirely 
      - name: Build client-side only files
        run: |
          npm run build
          [ -d ".output/public" ] && cp -r .output/public dist || echo "Using default dist directory"
        env:
          NUXT_APP_BASE_URL: '/clean-day/'
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4