name: Deploy Nuxt site to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: nuxt
      
      - name: Install dependencies
        run: npm ci
      
      - name: Update nuxt.config.ts
        run: |
          cat > nuxt.config.ts << EOF
          export default defineNuxtConfig({
            ssr: false,
            app: {
              baseURL: '/clean-day/'
            },
            nitro: {
              preset: 'github-pages',
              prerender: {
                failOnError: false,
                crawlLinks: false,
                routes: ['/']
              }
            },
            devtools: { enabled: true },
            typescript: {
              strict: true
            },
            experimental: {
              renderJsonPayloads: true
            }
          })
          EOF
      
      - name: Build client-side only files
        run: npm run build
        env:
          NUXT_APP_BASE_URL: '/clean-day/'
      
      # Create essential GitHub Pages files
      - name: Create GitHub Pages special files
        run: |
          # Create .nojekyll file to bypass Jekyll processing
          touch .output/public/.nojekyll
          
          # Ensure the dist directory exists
          mkdir -p dist
          
          # Copy all files from .output/public to dist
          cp -r .output/public/* dist/
          
          # Create .nojekyll in dist too
          touch dist/.nojekyll
          
          # Create a 404.html that redirects to index.html
          cat > dist/404.html << EOF
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Clean Day App</title>
              <script>
                // Redirect all 404s to index.html for SPA routing
                sessionStorage.setItem('redirectPath', window.location.pathname);
                window.location.href = '/clean-day/';
              </script>
            </head>
            <body>
              <p>Redirecting...</p>
            </body>
          </html>
          EOF
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4